server.port=8081
spring.application.name=vitalinkapp-historia

spring.datasource.url=jdbc:mysql://localhost:3304/db_historia?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root_pass_historia
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/