server:
  port: 8081
logging:
  level:
    org:
      springframework:
        security: TRACE
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3301/db_auth?serverTimezone=UTC
    password: root_pass_auth
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  application:
    name: vitalinkapp-auth
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/