server:
  port: 8080 # El puerto público por donde entrarán todas las peticiones móviles/web

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # Configuración global de CORS (Crucial para que un frontend web pueda consumirlo sin errores)
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*" # En producción cambia el * por la URL de tu frontend
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

      # Definición de rutas
      routes:
      # Ruta hacia tu microservicio de Autenticación
        - id: ruta-autenticacion
          uri: lb://VITALINKAPP-AUTH # 'lb' significa Load Balancer. Busca en Eureka el servicio con este nombre.
          predicates:
            - Path=/api/auth/** # Cualquier petición que empiece con esto, se manda al AUTH-SERVICE
        # Ruta hacia tu microservicio de Citas
        - id: ruta-citas
          uri: lb://VITALINKAPP-CITAS
          predicates:
            - Path=/api/especialidades/**,/api/medicos/**,/api/pacientes/**,/api/citas/**,/api/disponibilidades/**

        - id: ruta-historia
          uri: http://localhost:8083
          predicates:
            - Path=/api/historia-clinica/**,/api/consultas/**,/api/diagnosticos/**,/api/prescripciones/**
# Conexión al servidor Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/